#! /bin/sh
#
# Example panel for lemonbar

source ~/.config/colors/current

#num_mon=$(bspc query -M | wc -l)

function createWorkspace {
	#create reference with -n
	declare -n wmInfos=$2
	
	item=$1
	name=${item#?}
	
	unset FG
	unset BG
	
	case $item in
        	f*)
                	# free desktop
                        FG=$COLOR_FG
                        BG=$COLOR_BG
                        ;;
                F*)
                        # focused free desktop
                        FG=$COLOR_BG
                        BG=$COLOR_FG
                        ;;
                o*)
                        # occupied desktop
                        FG=$WHITE
                        BG=$COLOR_BG
                        ;;
                O*)
                        # focused occupied desktop
                        FG=$WHITE
                        BG=$COLOR_FG
                        ;;
                u*)
                        # urgent desktop
                        FG=$RED
                        BG=$COLOR_BG
                        ;;
                U*)
                        # focused urgent desktop
                        FG=$RED
                        BG=$COLOR_FG
                        ;;
		[LTG]*)
                        # layout, state and flags
                        wmInfos="${wmInfos}%{F$COLOR_FG}%{B$COLOR_BG} ${name}%{B-}%{F-}"
                        ;;
        esac
	if [ "$BG" ] && [ "$FG" ]; then
		wmInfos="${wmInfos}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
	fi

}

while read -r line; do
	
	declare -A workspaceInfos
	workspaceCount=-1
	
	case $line in
		V*)
			#Volume
			volume="%{F$COLORS_FG}%{B$COLOR_BG} ${line#?} %{B-}%{F-}"
			;;
		B*)
			#Battery
			battery="%{F$COLOR_FG}%{B$COLOR_BG} ${line#?} %{B-}%{F-}"
			;;
		S*)
			# clock output
			curClock="%{F$COLOR_FG}%{B$COLOR_BG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_FG}%{B$COLOR_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						unset workspaceInfo
						let "workspaceCount++"
						case $item in
                                  			m*)
                                          			# monitor
                                          			FG=$COLOR_FG
                                          			BG=$COLOR_BG
                                          			;;
                                  			M*)
                                          			# focused monitor
                                          			FG=$WHITE
                                          			BG=$BLUE
                                          			;;
                         			esac
						workspaceInfo="%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuULTG]*)
						createWorkspace $1 workspaceInfo
						;;
				esac
				workspaceInfos[$workspaceCount]=${workspaceInfo}
				shift
			done
			;;
	esac
	
	unset otherInfos
	for i in "${!workspaceInfos[@]}"; do
		if [ $i -gt 0 ]; then
   			otherInfos="${otherInfos}%{S+}%{l}${workspaceInfos[$i]}%{r}${curClock}"
		fi	
	done
	printf "%s\n" "%{l}${workspaceInfos[0]}${title}%{r}${volume}${battery}${curClock}${otherInfos}"
	
done
