#!/bin/sh

source $HOME/.config/colors/current
source $HOME/.scripts/common.sh

VPN_PID=/var/run/dhclient*.pid

function printVpn() {
	if [ -e $VPN_PID ]; then
		echo $(printWithFG $GREEN "vpn")" on"
	else	
		echo "vpn off"
	fi
}
