#!/bin/sh

source $HOME/.scripts/common.sh
source $HOME/.config/colors/current

BAT_LOW=25
BAT_EMPTY=10
function printBatteryInfo() {
	local BAT=/sys/class/power_supply/CMB1
	
	if [ -d $BAT ]; then
		local consumption=$(echo - | awk "{printf \"%.2f\", $((  $(cat $BAT/current_now) * $(cat $BAT/voltage_now) )) / 1000000000000 }")
         
		local status=$(cat $BAT/status)
	 	local remaining=$(acpi --battery | cut -d' ' -f5)
	 	if [ "$status" == "Charging" ]; then
			echo "$(printWithFG $YELLOW ) $(cat $BAT/capacity) ${remaining}"
         	elif [ "$status" == "Discharging" ]; then
			local cap=$(cat $BAT/capacity)
			local colorState=$GREEN
			if [ $cap -lt $BAT_LOW ]; then
				colorState=$ORANGE
			elif [ $cap -lt $BAT_EMPTY ]; then
				colorState=$RED
			fi
			echo "$(printWithFG $colorState ) $cap% ${remaining} (${consumption}W)"
         	else
			echo "$(printWithFG $YELLOW ) AC"
         	fi
	else
		echo "$(printWithFG $YELLOW ) AC"
	fi
}

#if type "acpi" >/dev/null 2>&1  && acpi --battery 2>&1|grep -qv "No support for device" ; then
#	while true; do
#       		echo "B $(printBatteryInfo)"
#       		sleep 20
#	done
#fi
