#!/bin/sh

source ${HOME}/.scripts/common.sh

printBatteryInfo() {
	local BAT=/sys/class/power_supply/CMB1

	if [ -d $BAT ]; then
		local consumption=$(echo - | awk "{printf \"%.2f\", $((  $(cat $BAT/current_now) * $(cat $BAT/voltage_now) )) / 1000000000000 }")
         
		local status=$(cat $BAT/status)
	 	local remaining=$(acpi --battery | cut -d' ' -f5)
	 	if [ "$status" == "Charging" ]; then
			echo " "$(cat $BAT/capacity)" ${remaining}"
         	elif [ "$status" == "Discharging" ]; then
			echo " "$(cat $BAT/capacity)"% ${remaining} (${consumption}W)"
         	else
			echo " AC"
         	fi
	else
		echo " AC"
	fi
}

#if type "acpi" >/dev/null 2>&1  && acpi --battery 2>&1|grep -qv "No support for device" ; then
#	while true; do
#       		echo "B $(printBatteryInfo)"
#       		sleep 20
#	done
#fi
	

