#!/bin/sh

source $HOME/.scripts/common.sh
source $HOME/.config/colors/current

function printVolume() {
	volStatus=$(amixer get Master | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq)     
	volLevel=$(amixer -M get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq) 
	         
	if [ "$volsStatus" == "off" ]; then     
		 echo "V$(printWithFG $RED ) $volLevel%"
	 else    
	         echo "V$(printWithFG $GREEN ) $volLevel%"
         fi
}
while true; do
	printVolume	
	sleep 5
done
