#!/bin/sh
if [ "17" = "$1" ]; then
    echo "Switch to java 17"
    sudo archlinux-java set java-17-openjdk
elif [ "11" = "$1" ]; then
    echo "Switch to java 11"
    sudo archlinux-java set java-11-openjdk
else
    echo "Version $1 not found or no version provided. Fallback to java 8"
    sudo archlinux-java set java-8-openjdk
fi

RESULT=$?
if [ "$RESULT" = "0" ]; then
    echo "Switch was successful"
else
    echo "Switch failed. Exit code $CODE"
fi

exit $CODE
