---
- name: "Create dir {{ aur_dir }}"
  ansible.builtin.file:
    path: "{{ aur_dir }}"
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory

- name: print user
  command: whoami
  register: username_on_the_host

- debug: var=username_on_the_host.stdout

# - name: Install AUR packages
#   include_tasks: tasks/helper/aur_download.yml
#   args:
#     apply:
#       become_user: "{{ user }}"
#   with_items:
#   - visual-studio-code-bin
#   - nvm
#   - google-chrome
#   loop_control:
#     loop_var: aur_package
