---
- name: "Create dir {{ aur_dir }}"
  ansible.builtin.file:
    path: "{{ aur_dir }}"
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory

- shell: whoami
  register: c

- shell: whoami
  become_user: "{{ user }}"
  register: d

- debug: var=c.stdout

- debug: var=d.stdout

- name: Install AUR packages
  include_tasks: tasks/helper/aur_download.yml
  args:
    apply:
      become_user: "{{ user }}"
  with_items:
  - visual-studio-code-bin
  - nvm
  - google-chrome
  loop_control:
    loop_var: aur_package
