---
- name: Check out dotfiles from personal repository
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    force: true
    recursive: true
    version: "{{ dotfiles_branch }}"

- name: Remove existing .bash_profile since we use .profile
  ansible.builtin.file:
    path: "/home/{{ user }}/.bash_profile"
    state: absent

- include_tasks: tasks/helper/link_file.yml
  args:
    apply:
      become_user: "{{ user }}"
  with_items:
    - .bash_logout
    - .bashrc
    - .bashrc.d
    - .bin
    - .profile
    - .scripts
    - .tmux.conf
    - .vimrc
    - .config/Code/User/settings.json # TODO does not exists on master yet
    - .config/base16-shell
    - .gnupg/gpg.conf
    - .gnupg/gpg-agent.conf
  loop_control:
    loop_var: file

- name: Install vim plugins
  ansible.builtin.command: "vim -es -u vimrc -i NONE -c 'PlugInstall' -c 'qa'"
  changed_when: false

- name: Ensure vim backup folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/.vim/backup"
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
