---
- name: Set hostname
  ansible.builtin.replace:
    path: /etc/hostname
    regexp: '^(.+)$'
    replace: '{{ hostname }}'
    group: root
    owner: root
    mode: 0644

- name: Ensure localhost is configured in hosts file
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    group: root
    owner: root
    state: present
    mode: 0644
  with_items:
    - regexp: '^127\.0\.0\.1.*localhost'
      line: "127.0.0.1        localhost"
    - regexp: '^::1.*localhost'
      line: "::1              localhost"
    - regexp: '^127\.0\.1\.1\s+\w+\.local\s+\w+$'
      line: "127.0.1.1        {{ hostname }}.local        {{ hostname }}"
