---
- name: Add pacman mirror
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^(\[extra]|\[core])\n(Include.*)'
    replace: '\1\nServer = {{ pacman_mirror }}\n\2'
    group: root
    owner: root
    mode: '0644'
