---
- name: Set timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    owner: root
    group: root
    mode: '0644'
    state: link

- name: Sync system with hardware time
  ansible.builtin.command: hwclock --systohc
  changed_when: false
