---
- name: Check if custom options already applied
  ansible.builtin.command: gsettings get org.gnome.desktop.input-sources xkb-options
  changed_when: false
  register: xkb_options

- name: Load dconf backup
  ansible.builtin.shell: "dbus-launch dconf load / < {{ dotfiles_dir }}/ansible/saved_settings.dconf"
  when: xkb_options.stdout != "['caps:escape']"

- name: Set git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Set git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
