---
- name: Change root Password
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"
    update_password: always
    state: present

- name: "Add user {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: always
    state: present

- name: "Ensure user {{ user }} is added to sudoers"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/001_{{ user }}"
    content: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
    mode: 0640
    validate: "visudo -cf %s"
