#!/bin/sh

#$HOME/.scripts/monitor.sh 
#$HOME/.scripts/monitor.sh workspaces

source $HOME/.config/colors/current

bspc config border_width         2
bspc config window_gap           2

bspc config top_padding 15

#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color of the border of an unfocused window.
bspc config normal_border_color $COLOR_FG

# Color of the bordeR of a focused window of an unfocused monitor.
bspc config active_border_color $ORANGE

# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color $WHITE

# Color of the presel message feedback.
bspc config presel_feedback_color $YELLOW

bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating

$HOME/.scripts/panel/panel &
#$HOME/.scripts/panel/panel_restart.sh &
