---
- hosts: localhost
  become: true
  gather_facts: false
  vars:
    - main_disk: "/dev/sda"
    - main_disk_password: "test123"
    - crypted_disk_name: cryptdisk

  tasks:
    - name: Setup hard drive
      include_tasks:
        file: tasks/storage.yml
        apply:
          tags:
            - storage
            - wipe
    - name: Prepare base system
      include_tasks: tasks/prepare_base.yml

- import_playbook: main.yml
  vars:
    connection_type: chroot
    hostlist: chroot
