---
- hosts: localhost
  become: true
  gather_facts: false
  vars:
    - main_disk: /dev/sda
    - main_disk_password: "test123"
    - crypted_disk_name: cryptdisk

  tasks:
    - name: Setup hard drive
      import_tasks: tasks/storage.yml
    - name: Prepare base system
      import_tasks: tasks/prepare_base.yml

- set_fact:
    hostlist: "{{ 'chroot' if 'chroot' in group_names else 'localhost' }}"

- import_playbook: main.yml
  tags:
    - always
