---
- hosts: localhost
  become: true
  gather_facts: false
  vars:
    - main_disk: /dev/sda
    - main_disk_password: "test123"
    - crypted_disk_name: cryptdisk

  tasks:
    - name: Setup hard drive
      import_tasks: tasks/storage.yml
    - name: Prepare base system
      import_tasks: tasks/prepare_base.yml

- import_playbook: main.yml
  vars:
    hostlist: "chroot"
  tags:
    - always
  when: "'chroot' in group_names"

- import_playbook: main.yml
  vars:
    hostlist: "localhost"
  tags:
    - always
  when: "'chroot' not in group_names"
