---
- hosts: localhost
  become: true
  gather_facts: false
  vars:
    - main_disk: /dev/sda
    - main_disk_password: "test123"
    - crypted_disk_name: cryptdisk

  tasks:
    - name: Running from iso?
      ansible.builtin.command: uname -a
      register: uname_out
    - name: Show facts
      debug: 
        var: uname_out.stdout
    - ansible.builtin.set_fact:
        hostlist: "{{ 'chroot' if 'archiso' in uname_out.stdout else 'localhost' }}"
        is_archiso: "{{ true if 'archiso' in uname_out.stdout else false }}"
        cacheable: yes
    - name: Setup hard drive
      import_tasks: tasks/storage.yml
      when: is_archiso == true
    - name: Prepare base system
      import_tasks: tasks/prepare_base.yml
      when: is_archiso == true

- import_playbook: main.yml
  tags:
    - always
