---
- hosts: localhost
  connection: "{{ connection_type }}"
  become: true
  gather_facts: false
  vars:
    - timezone: Europe/Berlin
    - root_password: password
    - user: test
    - user_password: password
    - hostname: test-workstation
    - aur_dir: "/home/{{ user }}/apps/aur"
    - dotfiles_repo: 'https://github.com/konstantinfoerster/dotfiles.git'
    - dotfiles_dir: "/home/{{ user }}/dotfiles"
    - git_user_name: "Tester"
    - git_user_email: "tester@mailinator.com"

  tasks:
    - name: Set timezone and sync hw clock
      include_tasks: tasks/time.yml
#     - name: Set correct language and keymap
#       include_tasks: tasks/language.yml
#     - name: Set hostname and add hosts
#       include_tasks: tasks/hostname.yml
#     - name: Configure grub
#       include_tasks: tasks/grub.yml
#     - name: Set root password and add user
#       include_tasks: tasks/user.yml
#     - name: Install packages
#       block:
#         - name: Install base packages
#           include_tasks: tasks/packages/base.yml
#         - name: Install video driver packages
#           include_tasks: tasks/packages/driver.yml
#         - name: Install audio packages
#           include_tasks: tasks/packages/audio.yml
#         - name: Install font packages
#           include_tasks: tasks/packages/font.yml
#         - name: Install terminal packages
#           include_tasks: tasks/packages/terminal.yml
#         - name: Install gnome packages
#           include_tasks: tasks/packages/gnome.yml
#         - name: Install vm and ops packages
#           include_tasks: tasks/packages/vm.yml
#         - name: Install development packages
#           include_tasks: tasks/packages/dev.yml
#         - name: Setup docker
#           include_tasks: tasks/packages/docker.yml
#         - name: Setup aur packages
#           include_tasks: tasks/aur.yml
#     - name: Apply user specific settings
#       become: false
#       become_user: "{{ user }}"
#       block:
#         - name: Apply user specific settings
#           include_tasks: tasks/user_settings.yml
#         - name: Setup dotiles
#           include_tasks: tasks/dotfiles.yml

# # TODO
# * Configure Chrome
