---
- hosts: "{{ hostlist | default('localhost') }}"
  connection: "{{ connection_type | default('local')  }}"
  become: true
  gather_facts: false
  vars:
    - main_disk: "/dev/sda"
    - timezone: Europe/Berlin
    - root_password: password
    - user: tester
    - user_password: password
    - hostname: test-workstation
    - aur_dir: "/home/{{ user }}/apps/aur"
    - dotfiles_repo: 'https://github.com/konstantinfoerster/dotfiles.git'
    - dotfiles_dir: "/home/{{ user }}/dotfiles"
    - dotfiles_branch: "setup-local-workstation-with-ansible"
    - git_user_name: "Tester"
    - git_user_email: "tester@mailinator.com"

  tasks:
    - name: Set timezone and sync hw clock
      import_tasks: tasks/time.yml
    - name: Set correct language and keymap
      import_tasks: tasks/language.yml
    - name: Set hostname and add hosts
      import_tasks: tasks/hostname.yml
    - name: Configure grub
      import_tasks: tasks/grub.yml
    - name: Set root password and add user
      import_tasks: tasks/user.yml
    - name: Install packages
      block:
        - name: Install base packages
          import_tasks: tasks/packages/base.yml
        - name: Install video driver packages
          import_tasks: tasks/packages/driver.yml
        - name: Install audio packages
          import_tasks: tasks/packages/audio.yml
        - name: Install font packages
          import_tasks: tasks/packages/font.yml
        - name: Install terminal packages
          import_tasks: tasks/packages/terminal.yml
        - name: Install gnome packages
          import_tasks: tasks/packages/gnome.yml
    #     - name: Install vm and ops packages
    #      import_tasks: tasks/packages/vm.yml
        # - name: Install development packages
        #   import_tasks: tasks/packages/dev.yml
        # - name: Install docker
        #   import_tasks: tasks/packages/docker.yml



    - name: Apply user specific setting
      #become_user: "{{ user }}"
      block:
        - name: print user
          command: whoami
          register: username_on_the_host
        - debug: var=username_on_the_host

        - name: print user
          become: true
          command: whoami
          register: username_on_the_host
        - debug: var=username_on_the_host

        - name: Setup aur packages
          import_tasks: tasks/aur.yml
        - name: Setup dotiles
          import_tasks: tasks/dotfiles.yml
        - name: Apply user specific settings
          import_tasks: tasks/user_settings.yml

# # TODO
# * Configure Chrome
