---
- name: "Checkout from aur repository for {{ aur_package }}"
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/{{ aur_package }}.git"
    dest: "{{ aur_dir }}/{{ aur_package }}"
    force: true
    update: true
    version: master
  register: aur

- name: "Reset git directory for {{ aur_package }}"
  ansible.builtin.command:
    cmd: git clean -xf # noqa command-instead-of-module remove files that are in .gitignore
    chdir: "{{ aur_dir }}/{{ aur_package }}"
  changed_when: false

- name: "Build package {{ aur_package }}"
  ansible.builtin.command:
    chdir: "{{ aur_dir }}/{{ aur_package }}"
    cmd: makepkg --force --syncdeps --rmdeps --clean --noconfirm
  changed_when: false
  when: aur.changed  # noqa no-handler

- name: "Find newly build package {{ aur_package }}"
  ansible.builtin.find:
    paths: "{{ aur_dir }}/{{ aur_package }}"
    patterns: '*.pkg.tar.zst'
  register: aur_build_packages

- name: "Install package {{ aur_package }}"
  community.general.pacman:
    name: "{{ aur_build_packages.files[0].path }}"
    state: present
  become: true
  become_user: root
  when: aur_build_packages.files | length == 1
