---
- name: "{{ aur_package }}: Checkout from aur repository"
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/{{ aur_package }}.git"
    dest: "{{ aur_dir }}/{{ aur_package }}"
    force: true
    update: true
    version: master

- name: "{{ aur_package }}: Reset git directory"
  ansible.builtin.command:
    cmd: git clean -xf # noqa command-instead-of-module remove files that are in .gitignore
    chdir: "{{ aur_dir }}/{{ aur_package }}"
  changed_when: false

- name: "{{ aur_package }}: Build package"
  ansible.builtin.command:
    chdir: "{{ aur_dir }}/{{ aur_package }}"
    cmd: makepkg --force --syncdeps --rmdeps --clean --noconfirm
  changed_when: false

- name: "{{ aur_package }}: Find newly build package"
  ansible.builtin.find:
    paths: "{{ aur_dir }}/{{ aur_package }}"
    patterns: '*.pkg.tar.zst'
  register: aur_build_packages

- name: "{{ aur_package }}: Install package"
  community.general.pacman:
    name: "{{ aur_build_packages.files[0].path }}"
    state: present
  become: true
  become_user: "{{ root_user }}"
  become_method: sudo
  when: aur_build_packages.files | length == 1
