---
- name: Install audio packages
  community.general.pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - gst-plugin-pipewire
      - libpulse
      - wireplumber
    state: latest

- name: Enable pipewire-pulse service
  become_user: "{{ user }}"
  ansible.builtin.systemd:
    name: pipewire-pulse
    enabled: true
    scope: user
