---
- name: Install base system packages
  community.general.pacman:
    name:
      - networkmanager
      - base-devel
      - bash-completion
      - openssh
      - gnupg
      - git
      - man-db
      - pwgen
      - traceroute
      - ntp
      - dosfstools
    state: present

- name: Enable NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Enable ssh daemon
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started

- name: Enable ntp daemon
  ansible.builtin.systemd:
    name: ntpd
    enabled: true
    state: started
