---
- name: Install font packages
  community.general.pacman:
    name:
      - ttf-dejavu
      - ttf-droid
      - ttf-hack
      - ttf-hack-nerd # patched fonts for nvim-web-devicons
      - powerline-fonts
    state: present
