---
- name: Install desktop packages
  community.general.pacman:
    name:
      - gnome
      - gnome-tweaks
      - gdm
      - gnome-software-packagekit-plugin
    state: present

- name: Enable gdm
  ansible.builtin.systemd:
    name: gdm
    enabled: true
